# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filerpc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'filerpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfilerpc.proto\x12\x07\x66ilerpc\" \n\x0bHashRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\x1e\n\x0cHashResponse\x12\x0e\n\x06sha256\x18\x01 \x01(\t2H\n\rFileProcessor\x12\x37\n\x08HashFile\x12\x14.filerpc.HashRequest\x1a\x15.filerpc.HashResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filerpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HASHREQUEST']._serialized_start=26
  _globals['_HASHREQUEST']._serialized_end=58
  _globals['_HASHRESPONSE']._serialized_start=60
  _globals['_HASHRESPONSE']._serialized_end=90
  _globals['_FILEPROCESSOR']._serialized_start=92
  _globals['_FILEPROCESSOR']._serialized_end=164
# @@protoc_insertion_point(module_scope)
